### ISSUE TITLE
Use of unresolved identifier 'DispatchQueueAttributes'

### ISSUE THREAD

**Issue by jstheoriginal** [ArtSabintsev/Zephyr#11]
Hey Arthur!

Just loaded this up in Xcode 8 beta 4 and I'm getting this error on line 75.

> Use of unresolved identifier 'DispatchQueueAttributes'

`private let zephyrQueue = DispatchQueue(label: "com.zephyr.queue", attributes: DispatchQueueAttributes.serial);`

It looks like this initializer is only available in iOS 10+.

**Comment by jstheoriginal** [comment]
Looks like it's actually just this for a serial queue now.

`private let zephyrQueue = DispatchQueue(label: "com.zephyr.queue")`

**Comment by ArtSabintsev** [comment]
Hey! My notifications have been kind of broken, so I just saw this issue.

I'll make the change in the swift3 branch - thanks!

**Comment by ArtSabintsev** [comment]
Is that in the release notes? Just looking around to confirm.

**Comment by jstheoriginal** [comment]
Doesn't look to be. Serial option is now gone in beta 4 though.

https://forums.developer.apple.com/thread/53398

**Comment by ArtSabintsev** [comment]
Yup, also the header-docs state the following:

```
At the core, dispatch provides serial FIFO queues...
```

**Comment by ArtSabintsev** [comment]
Done, updated for Xcode8b4. Enjoy!

**Comment by jstheoriginal** [comment]
weird...i was searching for serial in the documentation and couldn't find reference to that anywhere.

Thanks!

**Comment by ArtSabintsev** [comment]
See attached, 
<img width="684" alt="screen shot 2016-08-03 at 5 49 26 pm" src="https://cloud.githubusercontent.com/assets/854860/17383192/a49db560-59a2-11e6-9c37-67948e5b4074.png">
