### ISSUE TITLE
Best Implementation?

### ISSUE THREAD

**Issue by aabosh** [ArtSabintsev/Zephyr#16]
Hi,

I'm implementing Zephyr in my app now and I'm curious on what you believe is the best implementation of the library. Currently, in `AppDelegate`'s `didFinishLaunchingWithOptions()`, I run:
```
Zephyr.sync(keys: "presets", "selectedTheme")
Zephyr.addKeysToBeMonitored(keys: "presets", "selectedTheme")
```
However, some users seem to be experiencing a crash on launch and I've narrowed it down to these two lines of code. Am I using Zephyr wrong? If so, could you explain a better approach?

Thanks so much for the library, I've used it before the Swift 3 update and it's phenomenal.

**Comment by ArtSabintsev** [comment]
Hey - thanks for being an avid user!

I'd alternate the order in which you're calling the two lines of code, though it shouldn't cause any issues in your current implementation. 

Do you have a stacktrace you can provide me with?

**Comment by ArtSabintsev** [comment]
Closing this issue as there's been no response. Feel free to respond and I'll follow up.

**Comment by aabosh** [comment]
Sorry,

After finally getting the TestFlight logs (took 48+ hours), it turns out Zephyr was not the cause of the crash. Thanks again for the help and sorry for the late reply!

**Comment by ArtSabintsev** [comment]
No problem! Always happy to help!

Good luck fixing the problem!
