### ISSUE TITLE
Carthage Error: Dependency "Zephyr" has no shared framework schemes

### ISSUE THREAD

**Issue by jstheoriginal** [ArtSabintsev/Zephyr#18]
Hey Arthur,

Getting this error which I didn't get on 2.0.0 trying to update Zephyr via Carthage.

*** Checking out Zephyr at "2.1.0"
*** xcodebuild output can be found in /var/folders/kr/y2y78_m56yqckp9bb2wj0l0h0000gn/T/carthage-xcodebuild.OgXngT.log
*** Skipped building Zephyr due to the error:
Dependency "Zephyr" has no shared framework schemes

**Comment by jstheoriginal** [comment]
Looks like you just need to re-share the schemes that were removed in 2.1.0.

**Comment by ArtSabintsev** [comment]
Yup, my bad! Made some changes to the sample project and forgot to do that. 

As you can tell, I still never use Carthage 😝

**Comment by ArtSabintsev** [comment]
Fixed and re-tagged the new commit as 2.1.0. Try now.
