### ISSUE TITLE
Remove data from iCloud

### ISSUE THREAD

**Issue by gianpispi** [ArtSabintsev/Zephyr#19]
Hi! 

Is it possible to remove a specific key from iCloud, or does the removeKeysFromBeingMonitoredWithKeys method remove also the keys?

Thank you very much,

Gianpiero

**Comment by ArtSabintsev** [comment]
Hi,

I'm pretty sure it gets removed if the value for a key is set to nil.

See https://github.com/ArtSabintsev/Zephyr/blob/master/Zephyr/Zephyr.swift#L284 and the code surrounding it.

**Comment by gianpispi** [comment]
Thank you very much!

Cheers,

Gianpiero
