### ISSUE TITLE
[OSX] UIApplicationWillEnterForegroundNotification is iOS only

### ISSUE THREAD

**Issue by vlafiser** [ArtSabintsev/Zephyr#2]
![screenshot 2015-11-24 20 25 00](https://cloud.githubusercontent.com/assets/2131059/11381003/667d1bd6-92f1-11e5-9b1a-1cbfe241e20e.png)

Is it iOS thing only, viz. doc: https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplication_Class/#//apple_ref/c/data/UIApplicationWillEnterForegroundNotification

**Comment by ArtSabintsev** [comment]
I think we took care of this over Twitter, so we're all good now.

**Comment by vlafiser** [comment]
It not works, can you take a look on that please?

Thanks!

**Comment by ArtSabintsev** [comment]
It's because Zephyr was built for iOS, not OSX.

**Comment by vlafiser** [comment]
But it's here a way to port it also for OSX? I think that can be really good feature for your awesome library!

**Comment by ArtSabintsev** [comment]
ya, just remove the code that deals with that notification and you should be fine. That code is to perform a re-sync when iOS app comes back from the background.

**Comment by aabosh** [comment]
Getting this error and I'm working with iOS, any ideas?

**Comment by ArtSabintsev** [comment]
UIApplicationWillEnterForegroundNotification has been around since iOS 4. Not sure why you'd be getting that error in an iOS app.

**Comment by janheiermann** [comment]
If you use Zephyr in a framework where UIApplication is not available (aka "Allow app extension API only" is checked in your project settings), your can't use any of UIApplication's notification. You then have to move the notification code into your main app and process it from there.

Hope it helps ;-)
