### ISSUE TITLE
Background sync not triggered

### ISSUE THREAD

**Issue by evanrobertson** [ArtSabintsev/Zephyr#25]
I'm currently trying to get this set up to allow me to sync an array between devices.

In my AppDelegate I add

    Zephyr.debugEnabled = true
    Zephyr.addKeysToBeMonitored(keys: "defaultToSync")
    Zephyr.sync(keys: "defaultToSync")

Which when launching the second device will pull in what value has been set.

I then change the value using:

    UserDefaults().set(value, forKey: "defaultToSync")
    Zephyr.sync(keys: "defaultToSync")

My second device never seems to pick up that things have changed, the device making the change does say it has synced TO iCloud.

My understanding is that the key being monitored should at some point see the change?

Any help is appreciated.

**Comment by ArtSabintsev** [comment]
Thanks for the report. I'll take a look today.

From experience, I know it's not instantaneous - when/how-often to sync is under Apple's control. Mind doing a test in which you wait 30-60 seconds between checking devices, or have you done that already?

**Comment by evanrobertson** [comment]
I gave it ~15 minutes just sitting and waiting on both devices. That is; getting them both to a point they had monitoring set up, then changing the defaults on device A, see the TO iCloud call, then waiting for device B to see some sort of change/log.

Device B will pull in the change if I call sync on it, however I thought the background monitoring would take care of that. The stuff I am syncing isn't time critical, I would just like it to be triggered within a decent period (~30 mins) otherwise I may need to find an alternative.

**Comment by ArtSabintsev** [comment]
Thanks for specific testing. I'll take a look in the next 24 hours and perform my own tests as well.

Thanks for your patience, and my apologies!

**Comment by ArtSabintsev** [comment]
Just curious: Do you have Key-Value Storage enabled in the Capabilities tab per the instructions? https://github.com/ArtSabintsev/Zephyr#setup

**Comment by evanrobertson** [comment]
I do. I assume the fact when I trigger a sync on a new device it gets the data down means that part is all working correctly?

**Comment by ArtSabintsev** [comment]
Yes, correct. Just making sure. Wanted to eliminate non-code-related issues before diving in. Thanks for the clarification!

**Comment by ArtSabintsev** [comment]
One more question. When you say `device`, you mean physical device, not simulator, correct?

**Comment by ArtSabintsev** [comment]
Alright, testing on to devices, doing an explicit sync does work (e.g., calling `sync()` explicitly). So, that pretty much narrows down the issue to one function.

https://github.com/ArtSabintsev/Zephyr/blob/master/Sources/Zephyr.swift#L369-L384

**Comment by evanrobertson** [comment]
So I was using the sim to set the value and a device for the update. Would the sim update not trigger an update on device when set? Even though it does get to the cloud.

**Comment by ArtSabintsev** [comment]
Nope, it wouldn't. It has to be on 2 physical devices. Anyway, I found the bug. Will push a fix in a moment.

**Comment by ArtSabintsev** [comment]
Fixed here: https://github.com/ArtSabintsev/Zephyr/releases/tag/3.0.1

Feel free to follow up if you're still having issues.
