### ISSUE TITLE
Trouble Syncing

### ISSUE THREAD

**Issue by daviddelmonte** [ArtSabintsev/Zephyr#26]
Hi, and thanks for your control. I must be doing something wrong.

I am using v.3.0.1.
I am testing on 2 devices (iPhone 6 and an iPad). Both are running iOS11.2

In my `didFinishLaunchingWithOptions` method, I'm calling
```

Zephyr.sync(keys: ["useAnimations"])
Zephyr.addKeysToBeMonitored(keys:  "useAnimations")
```

The "useAnimations" tag is used throughout, and I copied and pasted it into the lines above.

Should I give the sync on each device some time to run?
What if the app is open on both devices at the same time?

I'm also using CloudKit. Is there any interaction that could cause a problem?

Many thanks

David

**Comment by ArtSabintsev** [comment]
Hey - thanks for the kind words.

What exactly is the problem? Are syncs not going through? Are the values wrong? Is there a default value that is set each time in `didFinishLaunchingWithOptions`?

The more detailed information you provide the easier it will be to diagnose the issue.

**Comment by ArtSabintsev** [comment]
Also, I think you should:

- add keys to be monitored _before_ using sync
-  make sure you use the [Register UserDefaults API](https://developer.apple.com/documentation/foundation/userdefaults/1417065-register) per the guidelines of the README (which I will update now with some hot links).

**Comment by daviddelmonte** [comment]
Thanks Art, I’ll do as you suggest and get back to you, after a short trip.

**Comment by ArtSabintsev** [comment]
Closing this issue. Feel free to reopen it if you're still having trouble.

**Comment by daviddelmonte** [comment]
all good now. Thanks for the assist

**Comment by ArtSabintsev** [comment]
My pleasure! Thanks for following up!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
