### ISSUE TITLE
Sync finished callback

### ISSUE THREAD

**Issue by slxl** [ArtSabintsev/Zephyr#3]
hi, Arthur!

how do you think is it possible to implement this callback or delegate method being fired in the end of sync?
@ArtSabintsev

**Comment by ArtSabintsev** [comment]
The question is more of a 'why?' 

You can monitor when your values change by adding an observer to NSUserDefaults for the key you're interested in.

**Comment by slxl** [comment]
@ArtSabintsev pardonne moi :) thanks!

**Comment by ArtSabintsev** [comment]
No problem! Glad that helped!
