### ISSUE TITLE
[idea] allow callback on update from iCloud

### ISSUE THREAD

**Issue by robbiemu** [ArtSabintsev/Zephyr#32]
So if I load my prefs at the start .. a short while later they will be loaded from iCloud and with Zephyr, like magic, they're ready for me in userdefaults. But, I've already loaded my prefs. Sure, I could go check again, but it would be awesome if I received a notification for them or something. Actually, I think the most elegant way is with a callback, then I could just write:

Zephyr.sync() { /* (error:Error?) in */ }

**Comment by ArtSabintsev** [comment]
Feel free to open a PR with an example implementation :) 

Closing this issue in favor of a future PR - feel free to follow up inhere.

**Comment by robbiemu** [comment]
It's your repo, but I wouldn't treat a feature like a bug report and close it right away. Feature ideas can stay open to let the community think on it together

**Comment by ArtSabintsev** [comment]
Hey,

Thanks for following up. My apologies if you feel that way. Over the years, what I've seen happen over all my repos is that feature requests in the form of issues like this sit open without any real follow up (unless I have more pointed questions that I need to ask). The recorded successes I've had have all come from me recommending that the issue creator create an example PR and delineate clearly what they're trying to achieve. That does two things: 

1. It makes it clearer for me what it is that you are trying to achieve and how it would work for your scenario and your specific problem.
2. It shows me that this feature is important enough to at least one individual (i.e., you) that time was spent implementing it.

Keeping issues open has, more often than not, led to issues going stale and makes it look like I, the maintainer, am not maintaining the repo. 

I hope you understand where I am coming from.

Arthur

**Comment by robbiemu** [comment]
No worries Arthur if I get the opportunity I'll be happy to look through this code and might produce a PR. At the moment I am completing the latter half of my classes towards my masters and completing my Capstone proposal..  I'm actually in finals week this week for the summer semester. But yeah if I get the opportunity I will look at your library

**Comment by ArtSabintsev** [comment]
No problem! Thanks for understanding.

I look forward to any PR that you open up.

Best of luck on your finals and good luck on getting your proposal through!
