### ISSUE TITLE
Explanation of Register API as it relates to Zephyr

### ISSUE THREAD

**Issue by getaaron** [ArtSabintsev/Zephyr#34]
Hi @ArtSabintsev ! Hope you're well. Believe it or not, I'm finally getting around to trying Zephyr for the first time 😄 . I'm finding it really easy and straightforward to set up, just have one point of confusion:

From the README:

> To make sure there's no overwriting going on in a fresh installation of your app on a new device that's connected to the same iCloud account, make sure that your UserDefaults are registered ***BEFORE*** calling any of the Zephyr methods. One way to easily achieve this is by using the [UserDefaults Register API](https://developer.apple.com/documentation/foundation/userdefaults/1417065-register).

I don't really understand this and I was wondering if you could explain this a little more.

- What does it mean to "register" `UserDefaults`, or to "add the contents of [a] dictionary to the registration domain"? I've only ever saved to or read from `UserDefaults`.
- What are the potential negative side effects if I don't use the Register API before calling Zephyr?
- How should I call it when the app launches?
  - For example, would `UserDefaults.standard.register(defaults: ["foo": "bar"])` be sufficient?
    - What does this do, exactly?

**Comment by ArtSabintsev** [comment]
Hey! Will respond tonight

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment]
Hey,

Registering a `UserDefault` allows you to set a default value for a specific `default` without saving it to disk. If you save it to disk, it will trigger Zephyr to sync that value, as it would be the _newest/latest_ value. If you want to bring in existing values that are on iCloud from a previous session on another device, it's best to just register the default values and wait for the sync to occur via Zephyr to get the previous values for those `defaults` you're interested in.

Hope that makes sense!

Closing this issue, but feel free to follow up here or other channels as you see fit.

**Comment by getaaron** [comment]
Ah got it. So if I am assuming all values will be null by default, and I’m not setting any default values, I can ignore this?

**Comment by ArtSabintsev** [comment]
correct - as long as their null (or not set), you're good to go!
