### ISSUE TITLE
Need help!

### ISSUE THREAD

**Issue by dimabiserov** [ArtSabintsev/Zephyr#38]
Hello! It's a cool library, but I'm newbie and can’t understand, how to send data to the cloud, and how to get it from there? There is only a sync method in the GitHub documentation.

**Comment by ArtSabintsev** [comment]
Hey!

All you have to do is register or set a couple `UserDefaults` value and then run `sync()` to save them to the Cloud. On subsequent launches, the latest timestamped value will be synced back to each device that has your app installed. 

This paragraph describes what happens: https://github.com/ArtSabintsev/Zephyr#integrate-zephyr-into-your-app

What exactly are you unclear about? I'm happy to elaborate!

**Comment by dimabiserov** [comment]
> Hey!
> 
> All you have to do is register or set a couple `UserDefaults` value and then run `sync()` to save them to the Cloud. On subsequent launches, the latest timestamped value will be synced back to each device that has your app installed.
> 
> This paragraph describes what happens: https://github.com/ArtSabintsev/Zephyr#integrate-zephyr-into-your-app
> 
> What exactly are you unclear about? I'm happy to elaborate!

thx for answer!


but I need to do it manually (by pressing two different buttons) first send a copy of the data to the Icloud, and when I want to press the another button get data from Icloud to app, I do not need automatic syncronization

**Comment by ArtSabintsev** [comment]
Unfortunately, you cannot do that with the key-value store iCloud entitlement. Apple controls when and how it syncs. Usually, it’s instant syncing one way when you modify set/register a default. Getting values from iCloud is totally up to the system/OS.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dimabiserov** [comment]
this is very sad, thanks for the reply!
