### ISSUE TITLE
sync with value nil

### ISSUE THREAD

**Issue by luicm** [ArtSabintsev/Zephyr#40]
Hi, 
it is happening to me that when saving a Date in `UserDefaults` and then `sync` I get: 
`Synchronized key '....' with value 'nil'`
I am checking and the value is properly set, but after syncing is `nil` :( 
Any idea why this is happening?

**Comment by ArtSabintsev** [comment]
Hi, I need sample code examples how are you are using this library, otherwise it will be really hard to diagnose what’s going on.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment]
Closing due to lack of a response.
