### ISSUE TITLE
UIApplication.willEnterForegroundNotification not posted when using scene delegate

### ISSUE THREAD

**Issue by funkenstrahlen** [ArtSabintsev/Zephyr#42]
As far as I understand this change in iOS 13 `UIApplication.willEnterForegroundNotification` is no longer posted when using the new scene delegates as described here:

https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_foreground

Therefore listening to scene lifecycle notifications might be required.

What do you think?

**Comment by ArtSabintsev** [comment]
So just adding this, https://developer.apple.com/documentation/uikit/uiscene/3197925-willenterforegroundnotification, right?

**Comment by funkenstrahlen** [comment]
Yes that looks good to me!

**Comment by ArtSabintsev** [comment]
The change has been made on the `swift5.1` branch: https://github.com/ArtSabintsev/Zephyr/commit/81c97a2044f081fe53da7df0823d952d00952a80

**Comment by ArtSabintsev** [comment]
Easier to review this way: https://github.com/ArtSabintsev/Zephyr/pull/44
