### ISSUE TITLE
follow up override issue

### ISSUE THREAD

**Issue by luicm** [ArtSabintsev/Zephyr#46]
Sorry for my late response. 
answering your question here: https://github.com/ArtSabintsev/Zephyr/issues/45#event-2843850328

first in: 
`func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?)`

I register defaults, where: 
```swift
let emptyData = Data()
UserDefaults.standard.register(defaults: [subscription.identifier: emptyData])
Zephyr.addKeysToBeMonitored(keys: [subscription.identifier])
```

later after checking the status of the user subscription I store the subscription in UserDefaults to later sync: 
```swift
let encoder = PropertyListEncoder()
let statusData = try! encoder.encode(status)                
UserDefaults.standard.set(statusData, forKey: subscription.identifier)
Zephyr.sync(keys: [subscription.identifier])
```

And here is where the override issue happens. I managed to fix it in my phone by removing the key from iCloud with `NSUbiquitousKeyValueStore.default.removeObject(forKey:)`
But trying with a different phone happen again. 

If you could give me some hint here I would really appreciated

**Comment by ArtSabintsev** [comment]
Alright, this may take a bit of back and forth to resolve.

First, if you have monitoring turned on, you only ever have to call Sync once, and usually after monitoring is turned on. So, move the sync call to happen sooner. That might help solve this issue.

Here's what I do in my personal project (somewhat simplified for this example):

```swift
func setupZephyr() {
    UserDefaults.standard.register(defaults: [aKey: Data()])

    #if DEBUG
    Zephyr.debugEnabled = true
    #endif

    Zephyr.addKeysToBeMonitored(keys: aKey)
    Zephyr.sync(keys: aKey)
}
```

where `setupZephyr()` is called in the `didFinishLaunchingWithOptions` method.

**Comment by luicm** [comment]
oh ok! so it is not needed to sync every time I update the data in UserDefaults?

I will try that and let you know how it goes :)

**Comment by ArtSabintsev** [comment]
Thanks! Yes, if you are using the monitoring functionality, which you are, then it should just work. Please let me know.

**Comment by ArtSabintsev** [comment]
Hi - any update? I'm hoping we can close this issue :)

**Comment by luicm** [comment]
Hi, I have no updates yet, will text test today with several phones to see how it works, will write right after :)

**Comment by ArtSabintsev** [comment]
thank you!

**Comment by ArtSabintsev** [comment]
Hey, just following up! Thanks!

**Comment by ArtSabintsev** [comment]
Closing due to lack of follow up.
