### ISSUE TITLE
Issue with initial load from iCloud

### ISSUE THREAD

**Issue by aedificator-nl** [ArtSabintsev/Zephyr#48]
On an initial install of an app with Zephyr the iCloud data is not immediately available. Once it is available is should be synced with the current `UserDefaults`. This does not happen on an initial load however, as `keysDidChangeOnCloud` will return early if `localStoredDate` is nil (which it is as this is the initial load of the application). 

The issue seems to be in `keysDidChangeOnCloud:452`, have made a PR: #47.

**Comment by ArtSabintsev** [comment]
Let's discuss this in your open PR.

Thank you!
