### ISSUE TITLE
using Zephyr with a suiteName

### ISSUE THREAD

**Issue by TheApApp** [ArtSabintsev/Zephyr#49]
I am just getting started with Zephyr, I want to use it sync my UserDefaults between iPad and iOS version of my app.  I have set it up, and it doesn't seem to find the values across devices.  Both devices are logged into the same iCloud account, and in debug mode I see that Zephyr is syncing - but each devices seems to find a unique instance. (this is in the simulator on both devices).  Is this addressed via a UserDefaults SuiteName?

**Comment by ArtSabintsev** [comment]
That is quite strange. Can you provide more information? I have an app live in the store with this app that I test locally across devices, so I ca attempt to replicate your situation, if needed.

Also, Zephyr doesn't use suites.

**Comment by TheApApp** [comment]
I have added in the Zephyr sync - please check my git - https://github.com/TheApApp/WastedTimev10

**Comment by TheApApp** [comment]
I keep getting - `iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVConference.framework/AVConference (0x146cb13f0). One of the two will be used. Which one is undefined.
[Zephyr] Started synchronization FROM iCloud
[Zephyr] Unsubscribed 'syncKeyRateValue' from observation.
[Zephyr] Synchronized key 'syncKeyRateValue' with value 'nil' FROM iCloud
[Zephyr] Subscribed 'syncKeyRateValue' for observation.
[Zephyr] Unsubscribed 'syncKeyHourlySalaryBool' from observation.
[Zephyr] Synchronized key 'syncKeyHourlySalaryBool' with value 'nil' FROM iCloud
[Zephyr] Subscribed 'syncKeyHourlySalaryBool' for observation.
[Zephyr] Unsubscribed 'syncKeyTotalWastePeople' from observation.
[Zephyr] Synchronized key 'syncKeyTotalWastePeople' with value 'nil' FROM iCloud
[Zephyr] Subscribed 'syncKeyTotalWastePeople' for observation.
[Zephyr] Unsubscribed 'syscKeyTotalWasteAmount' from observation.
[Zephyr] Synchronized key 'syscKeyTotalWasteAmount' with value 'nil' FROM iCloud
[Zephyr] Subscribed 'syscKeyTotalWasteAmount' for observation.
[Zephyr] Unsubscribed 'syncKeyTotalWasteAmountPersonal' from observation.
[Zephyr] Synchronized key 'syncKeyTotalWasteAmountPersonal' with value 'nil' FROM iCloud
[Zephyr] Subscribed 'syncKeyTotalWasteAmountPersonal' for observation.
[Zephyr] Unsubscribed 'syncKeyTotalMeetingAmount' from observation.
[Zephyr] Synchronized key 'syncKeyTotalMeetingAmount' with value 'nil' FROM iCloud
[Zephyr] Subscribed 'syncKeyTotalMeetingAmount' for observation.
[Zephyr] Unsubscribed 'syncKeyTotalMeetingPeople' from observation.
[Zephyr] Synchronized key 'syncKeyTotalMeetingPeople' with value 'nil' FROM iCloud
[Zephyr] Subscribed 'syncKeyTotalMeetingPeople' for observation.
[Zephyr] Unsubscribed 'syncKeyTotalMeetingAmountPersonal' from observation.
[Zephyr] Synchronized key 'syncKeyTotalMeetingAmountPersonal' with value 'nil' FROM iCloud
[Zephyr] Subscribed 'syncKeyTotalMeetingAmountPersonal' for observation.
[Zephyr] Unsubscribed 'syncKeyTotalLifetimePeople' from observation.
[Zephyr] Synchronized key 'syncKeyTotalLifetimePeople' with value 'nil' FROM iCloud
[Zephyr] Subscribed 'syncKeyTotalLifetimePeople' for observation.
[Zephyr] Unsubscribed 'syncKeyTotalLifetimeMeetingAmount' from observation.
[Zephyr] Synchronized key 'syncKeyTotalLifetimeMeetingAmount' with value 'nil' FROM iCloud
[Zephyr] Subscribed 'syncKeyTotalLifetimeMeetingAmount' for observation.
[Zephyr] Unsubscribed 'syncKeyTotalLifeTimeTotalWasteAmount' from observation.
[Zephyr] Synchronized key 'syncKeyTotalLifeTimeTotalWasteAmount' with value 'nil' FROM iCloud
[Zephyr] Subscribed 'syncKeyTotalLifeTimeTotalWasteAmount' for observation.
[Zephyr] Finished synchronization FROM iCloud
2020-07-08 20:30:18.843752-0400 Wasted Time[3371:376195] [Scene Delegate] scene delegate
`

**Comment by TheApApp** [comment]
I received this every time, regardless of the device.. so something is not syncing... I hope that helps

**Comment by ArtSabintsev** [comment]
hey, unfortunately that does not help, and the link is probably marked private, as I cannot see it.

**Comment by TheApApp** [comment]
I still need to clean my keys out of the project so added you as a collaborator.  Thanks for lookin in.

**Comment by ArtSabintsev** [comment]
@TheApApp hey, I'll be transparent with you - I don't have any time to debug another project. 

I can show you my implementation, but that's about it:

```swift
    func setupZephyr() {
        UserDefaults.standard.register(defaults: [storesSyncKey: Data()]) // THIS LINE MAY HELP YOU

        #if DEBUG
            Zephyr.debugEnabled = true
        #endif

        if Settings.synchronizationEnabled { // THIS IS SPECIFIC TO MY APP
            Zephyr.addKeysToBeMonitored(keys: storesSyncKey)
        }
    }
```

**Comment by TheApApp** [comment]
Just wanted to close this out... I got the sync working, but since I need a suiteName it won't work. Thank you for creating zephyr and patience to respond to me.

**Comment by ArtSabintsev** [comment]
No problem! You can definitely fork and adapt zephyr to work with suites. I've just never had a need, so I didn't do it.

Best of luck!
