### ISSUE TITLE
Any reason macOS isn't listed as supported?

### ISSUE THREAD

**Issue by trentguillory** [ArtSabintsev/Zephyr#51]
I see `iOS` and `tvOS` as the supported platforms in the ReadMe _and_ in the code, but is there a reason `macOS` isn't listed as well?

**Comment by ArtSabintsev** [comment]
macOS works through Catalyst, that much I know. I don't think I've built a Mac app to test it to be honest. Feel free to try it out and make the requisite changes in the source code if you can prove it works.
