### ISSUE TITLE
Issue when changing multiple keys in macOS Monterey

### ISSUE THREAD

**Issue by paxos** [ArtSabintsev/Zephyr#53]
First off: Thank you for this library. This is exactly what I was looking for.

There seems to be a sync issue with macOS Monterey (tested version: 12.0.1 (21A558))

It seems that Apple changed the behavior on how it posts the `NSUbiquitousKeyValueStore.didChangeExternallyNotification` notification.

Formerly, `notification.userInfo?[NSUbiquitousKeyValueStoreChangedKeysKey]` contained ALL changed keys (including `ZephyrSyncKey`). In my tests, this is no longer the case. Instead, the notification gets posted multiple times, with different values. Here is what happens in my scenario:

We have Client A and Client B. Lets say A changes 2 keys. What happens is:

Zephyr:
  - Receives `NSUbiquitousKeyValueStore.didChangeExternallyNotification` notification for key 1, stores remote value to local user defaults.
  - Zeyphr sets local sync date
  - Receives `NSUbiquitousKeyValueStore.didChangeExternallyNotification` notification for key 2, throws it away, because local sync date is newer
  - Receives `NSUbiquitousKeyValueStore.didChangeExternallyNotification` notification for key `ZephyrSyncKey` 

https://github.com/ArtSabintsev/Zephyr/blob/d86fe8ccc70b599ffd9adde55ada042910d045a1/Sources/Zephyr.swift#L456-L459
 
In this scenario, the second value was thrown out and both apps are no longer in sync.

I can't tell if this is a (beta) bug or if this is the new, expected behavior. I can't think of a good way to fix this, as we would now need to store the sync date of each property - or somehow batch all those updates coming in.

**Comment by ArtSabintsev** [comment]
Thanks for the callout. 

If this is in a beta build, I'd wait it out. I don't know how to fix it either. If this turns out to be a massive problem then I'll spend some time thinking on it.

Let me know what you see in newer betas.

**Comment by paxos** [comment]
Forgot to mention: I also filled a radar. I can put it on Open Radar as well.

**Comment by ArtSabintsev** [comment]
That sounds like a great idea!

**Comment by ArtSabintsev** [comment]
Closing for now - please reopen if you still see this issue.

**Comment by paxos** [comment]
Issue is still existent on Monterey 12.0.1 as well as 12.1 Beta 1.

I would recommend reopening this. The library does not work in this form on Monterey unfortunately :-/

**Comment by paxos** [comment]
I confirmed that `keysDidChangeOnCloud` gets called with ALL changed keys on < Monterey, but multiple times with only 1 key on Monterey.

**Comment by ArtSabintsev** [comment]
Mind opening a new ticket? I'm ooto for a few more days. Will take it from there. 

Most likely will stop support macOS since I don't have time to really address this issue.

Arthur
