### ISSUE TITLE
Publishing changes from background threads is not allowed (SwiftUI)

### ISSUE THREAD

**Issue by marcheimendinger** [ArtSabintsev/Zephyr#56]
I'm getting a runtime issue while receiving changes from iCloud in a SwiftUI app which uses `@AppStorage` to access UserDefaults.

```
[SwiftUI] Publishing changes from background threads is not allowed; make sure to publish values from the main thread (via operators like receive(on:)) on model updates.
```

It's pointing to [this line](https://github.com/ArtSabintsev/Zephyr/blob/1d1c95017e96ea850f19e44ddf1bbd20344abd70/Sources/Zephyr.swift#L363) of code, which I believe should run on the main thread to avoid this issue?

**Comment by ArtSabintsev** [comment]
That's interesting. Feel free to open a PR. I'll play around with it when I have some time.

**Comment by ArtSabintsev** [comment]
Closing this issue in favor of a PR down the line.
