### ISSUE TITLE
Add watchOS 9 as target platform

### ISSUE THREAD

**Issue by funkenstrahlen** [ArtSabintsev/Zephyr#59]
[NSUbiquitousKeyValueStore is now also supported in watchOS 9](https://developer.apple.com/documentation/foundation/nsubiquitouskeyvaluestore). Currently Zephyr Swift package is not available on watchOS. Please add watchOS 9 as a target platform in the Package.swift.

**Comment by ArtSabintsev** [comment]
Feel free to open a PR! Thank you!

**Comment by ArtSabintsev** [comment]
Closing in favor of #60.
