### ISSUE TITLE
Async calls causing unsubscribe/subscribe process to fail

### ISSUE THREAD

**Issue by russellquinn** [ArtSabintsev/Zephyr#71]
There's a timing bug in `syncFromCloud` that causes the observers to be re-registered before the new value is actually written to `UserDefaults`, meaning the observers get fired.

When I run the app and it's in a FROM state (see Issue #70 where I describe this) then I'm seeing the following in the debug info. It pulls the iCloud version in, then immediately writes it back to iCloud (messing up the local/remote `Dates()`)
 
Here's an example log:

```
[Zephyr] Subscribed 'selectedCityTitle' for observation.
[Zephyr] Started synchronization FROM iCloud
[Zephyr] Unsubscribed 'selectedCityTitle' from observation.
[Zephyr] Synchronized key 'selectedCityTitle' with value 'Chicago' FROM iCloud
[Zephyr] Subscribed 'selectedCityTitle' for observation.
[Zephyr] Finished synchronization FROM iCloud
[Zephyr] Unsubscribed 'selectedCityTitle' from observation.
[Zephyr] Synchronized key 'selectedCityTitle' with value 'Chicago' TO iCloud.
[Zephyr] Subscribed 'selectedCityTitle' for observation.
```  

Looking at the code in `syncFromiCloud`:

```
        unregisterObserver(key: key)

        if let value = value {
            DispatchQueue.main.async { defaults.set(value, forKey: key) }
            Zephyr.printKeySyncStatus(key: key, value: value, destination: .local)
        } else {
            DispatchQueue.main.async { defaults.set(nil, forKey: key) }
            Zephyr.printKeySyncStatus(key: key, value: nil, destination: .local)
        }

        Zephyr.postNotificationAfterSyncFromCloud()

        registerObserver(key: key)
  ```

The actual `defaults.set(...)` are wrapped in an `async` so they get called _after_ `registerObserver` is activated again.

If I add print statements for `Writing to UserDefaults` into the `async`s to visualize the timing, it shows this happening. The subscribe happens before the data is set.

```
[Zephyr] Subscribed 'selectedCityTitle' for observation.
[Zephyr] Started synchronization FROM iCloud
[Zephyr] Unsubscribed 'selectedCityTitle' from observation.
[Zephyr] Synchronized key 'selectedCityTitle' with value 'Chicago' FROM iCloud
[Zephyr] Subscribed 'selectedCityTitle' for observation.
[Zephyr] Finished synchronization FROM iCloud
Writing to UserDefaults
[Zephyr] Unsubscribed 'selectedCityTitle' from observation.
[Zephyr] Synchronized key 'selectedCityTitle' with value 'Chicago' TO iCloud.
[Zephyr] Subscribed 'selectedCityTitle' for observation.
```

**Comment by ArtSabintsev** [comment]
Hey, thanks for the PR. 

I am no longer doing iOS engineering and have no time to maintain this repo. I'm going to public archive it.

Feel free to fork it and address the issue(s) as you see fit.
