### ISSUE TITLE
Config and use NSUserDefaults with app group

### ISSUE THREAD

**Issue by dzpt** [ArtSabintsev/Zephyr#9]
I'm want to sync NSUserDefaults from app group like:

`NSUserDefaults(suiteName: "group.xxx")`

But there's no way to do with Zephyr.

**Comment by ArtSabintsev** [comment]
Ah yes, I haven't added support for suites. It's on my to-do list - thanks!

Fee free to tackle it and open a PR if you want!

**Comment by ArtSabintsev** [comment]
I've been thinking about this feature and doing some research over the last few days.

I don't think there's an easy way to accomplish this feat. 

The main issue is that **NSUbiquitousKeyValueStore** does not have a `suite`-style analog to **NSUserDefaults**. This means that any keys we try syncing from `NSUserDefaults(suiteName:)` _MUST_ be exposed outside the suite at the point of synchronization.

A solution would be to save all of the suite-related keys into a **dictionary** on `standardUserDefaults` and sync that dictionary. It still exposes and populates all of your keys to the `standardUserDefaults`, but they're tucked away in a dictionary that you can then perform _diffs_ on.

If one-or-more keys were changed, overwrite the values for the keys in the suite with the ones that you received back in `standardUserDefaults`, and you're back in business!

Unfortunately, I don't see anyway around this scenario.

Thanks for the suggestion and sorry that I can't do much more!
